name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check out teh code
        uses: actions/checkout@v3
      - name: upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
